version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO__USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO__PASSWORD}
    volumes:
      - .db:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO__USERNAME}:${MONGO__PASSWORD}@mongo:27017/
