[tool.isort]
py_version=39
profile="black"
skip_glob=".venv/*"

[tool.autoflake]
in-place=true
remove-duplicate-keys=true
remove-unused-variables=true
remove-all-unused-imports=true
recursive=true
exclude=".venv"

[tool.pylint]
disable=["raw-checker-failed", "too-many-locals", "too-many-instance-attributes", "too-many-arguments", "fixme", "missing-timeout", "broad-exception-caught", "too-few-public-methods", "bad-inline-option", "locally-disabled", "file-ignored", "suppressed-message", "useless-suppression", "deprecated-pragma", "use-symbolic-message-instead", "use-implicit-booleaness-not-comparison-to-string", "use-implicit-booleaness-not-comparison-to-zero", "missing-module-docstring", "missing-class-docstring", "missing-function-docstring"]
ignore-paths=".venv/*"